### ISSUE TITLE
Video Loaded But Not Automatically Starting (not autoplaying)

### ISSUE THREAD

**Issue by xymantec** [akv2/MaxImage#43]
I have gotten the video to load into the slide but it will not autoplay, I have used the correct HTML tags and it still won't autoplay, Is there something else I can do to make the video play? 

```
<div class="slides-container">
      <img src="images/people.jpeg" alt="Cinelli">
      <video class="html5video" preload="auto" autoplay loop="loop"><source src="video.mp4" type="video/mp4" /></video>
      <img src="images/surly.jpeg" width="1024" height="682" alt="Surly">
      <img src="images/cinelli-front.jpeg" width="1024" height="683" alt="Cinelli">
      <img src="images/affinity.jpeg" width="1024" height="685" alt="Affinity">
      
    </div>
```

I have literally tried everything HTML but nothing js, is there an internal function I have to use?

**Comment by ronan-paul** [comment]
Hello
Did you manage to mix pictures and video nicely ? I mean playing video automatically and loading next content after video end ?
